<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Crear una categoría si no existe
        $categoryId = DB::table('f1collector_categories')->updateOrInsert([
            'name' => 'Fórmula 1',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('f1collector_products')->insert([
            [
                'name' => 'Red Bull RB19 - Verstappen',
                'price' => 69.99,
                'team' => 'Red Bull Racing',
                'year' => 2023,
                'category_id' => $categoryId,
                'image' => 'images/redbull.webp',
                'description' => 'Modelo a escala 1:18 del Red Bull RB19, campeón del mundo con Max Verstappen en 2023.',
                'type' => 'Escala 1:18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ferrari SF-23 - Leclerc',
                'price' => 59.99,
                'team' => 'Ferrari',
                'year' => 2023,
                'category_id' => $categoryId,
                'image' => 'images/ferrari.webp',
                'description' => 'Modelo a escala 1:18 del Ferrari SF-23 conducido por Charles Leclerc en 2023.',
                'type' => 'Escala 1:18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mercedes W14 - Hamilton',
                'price' => 64.99,
                'team' => 'Mercedes',
                'year' => 2023,
                'category_id' => $categoryId,
                'image' => 'images/mercedes.webp',
                'description' => 'Modelo a escala 1:18 del Mercedes W14 pilotado por Lewis Hamilton en 2023.',
                'type' => 'Escala 1:18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alpine A523 - Gasly',
                'price' => 55.99,
                'team' => 'Alpine',
                'year' => 2023,
                'category_id' => $categoryId,
                'image' => 'images/alpine.webp',
                'description' => 'Modelo a escala 1:18 del Alpine A523 conducido por Pierre Gasly en 2023.',
                'type' => 'Escala 1:18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'McLaren MCL60 - Norris',
                'price' => 62.99,
                'team' => 'McLaren',
                'year' => 2023,
                'category_id' => $categoryId,
                'image' => 'images/mclaren.webp',
                'description' => 'Modelo a escala 1:18 del McLaren MCL60 pilotado por Lando Norris en 2023.',
                'type' => 'Escala 1:18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alfa Romeo C43 - Bottas',
                'price' => 57.99,
                'team' => 'Alfa Romeo',
                'year' => 2023,
                'category_id' => $categoryId,
                'image' => 'images/alfaromeo.webp',
                'description' => 'Modelo a escala 1:18 del Alfa Romeo C43 conducido por Valtteri Bottas en 2023.',
                'type' => 'Escala 1:18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aston Martin AMR23 - Alonso',
                'price' => 60.99,
                'team' => 'Aston Martin',
                'year' => 2023,
                'category_id' => $categoryId,
                'image' => 'images/aston.webp',
                'description' => 'Modelo a escala 1:18 del Aston Martin AMR23 pilotado por Fernando Alonso en 2023.',
                'type' => 'Escala 1:18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Haas VF-23 - Magnussen',
                'price' => 54.99,
                'team' => 'Haas',
                'year' => 2023,
                'category_id' => $categoryId,
                'image' => 'images/haas.webp',
                'description' => 'Modelo a escala 1:18 del Haas VF-23 conducido por Kevin Magnussen en 2023.',
                'type' => 'Escala 1:18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AlphaTauri AT04 - Tsunoda',
                'price' => 56.99,
                'team' => 'AlphaTauri',
                'year' => 2023,
                'category_id' => $categoryId,
                'image' => 'images/vicarb.webp',
                'description' => 'Modelo a escala 1:18 del AlphaTauri AT04 pilotado por Yuki Tsunoda en 2023.',
                'type' => 'Escala 1:18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Williams FW45 - Albon',
                'price' => 53.99,
                'team' => 'Williams',
                'year' => 2023,
                'category_id' => $categoryId,
                'image' => 'images/williams.webp',
                'description' => 'Modelo a escala 1:18 del Williams FW45 conducido por Alex Albon en 2023.',
                'type' => 'Escala 1:18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Scuderia Ferrari F1-2000 - Schumacher',
                'price' => 69.90,
                'team' => 'Ferrari',
                'year' => 2000,
                'category_id' => $categoryId,
                'image' => 'images/ferrai-Schumi.jpg',
                'description' => 'Réplica oficial del Ferrari F1-2000, utilizado por Michael Schumacher en el Gran Premio de Europa de Fórmula 1 de 2000.',
                'type' => 'Escala 1:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'McLAREN MP 4/4 - Senna',
                'price' => 69.90,
                'team' => 'McLaren',
                'year' => 1988,
                'category_id' => $categoryId,
                'image' => 'images/mcl-senna.jpg',
                'description' => 'Réplica oficial del McLaren MP4/4, utilizado por Ayrton Senna en el Gran Premio de Mónaco de Fórmula 1 de 1988.',
                'type' => 'Escala 1:24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HAAS VF 21 - Mazepin',
                'price' => 69.90,
                'team' => 'Uralkali Haas F1 Team',
                'year' => 2021,
                'category_id' => $categoryId,
                'image' => 'images/mazepin.jpg',
                'description' => 'Réplica oficial del Haas VF-21, utilizado por Nikita Mazepin en 2021.',
                'type' => 'Escala 1:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lotus 72D - Fittipaldi',
                'price' => 69.90,
                'team' => 'Lotus',
                'year' => 1972,
                'category_id' => $categoryId,
                'image' => 'images/lotus.jpg',
                'description' => 'Réplica oficial del Lotus 72D, utilizado por Emerson Fittipaldi.',
                'type' => 'Escala 1:24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'McLAREN M23 - James Hunt',
                'price' => 39.90,
                'team' => 'McLaren',
                'year' => '1976',
                'category_id' => $categoryId,
                'image' => 'images/hunt.jpg',
                'description' => 'Réplica oficial del McLaren M23, utilizado por James Hunt en 1976.',
                'type' => 'Escala 1:24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Renault R25 - Fernando Alonso',
                'price' => 9999.99,
                'team' => 'Renaul. F1 Team',
                'year' => '2005',
                'category_id' => $categoryId,
                'image' => 'images/r25.jpg',
                'description' => 'Réplica oficial del Renault R25, monoplaza campeón del mundo en 2005, pilotado por Fernando Alonso.',
                'type' => 'Escala 1:18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'McLAREN MP 4/23 Lewis Hamilton',
                'price' => 23.97,
                'team' => 'McLaren Mercedes',
                'year' => '2008',
                'category_id' => $categoryId,
                'image' => 'images/vodafone.jpg',
                'description' => 'Réplica oficial del McLaren MP4/23, monoplaza campeón del mundo en 2008, pilotado por Lewis Hamilton.',
                'type' => 'Escala 1:43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}